# Change these first
owner: ErdbeerbaerLP # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository
user-agent: ErdbeerbaerLP
sites:
  - name: Maven Repo
    url: https://repo.erdbeerbaerlp.de
  - name: Discord Integration API
    url: https://api.erdbeerbaerlp.de/dcintegration/
    expectedStatusCodes:
    - 404
  - name: Mastodon
    url: https://mastodon.erdbeerbaerlp.de
  - name: Switch LAN-Play Server
    check: "tcp-ping"
    url: erdbeerbaerlp.de
    port: 11451
  - name: Discord Integration Minecraft Server
    check: "tcp-ping"
    url: erdbeerbaerlp.de
    port: 25565

status-website:
  cname: status.erdbeerbaerlp.de
  theme: dark
  name: ErdbeerbaerLP
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
