# Change these first
owner: ErdbeerbaerLP # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Maven Repo
    url: https://repo.erdbeerbaerlp.de
  - name: Discord Integration API
    url: https://api.erdbeerbaerlp.de/dcintegration/
    expectedStatusCodes:
    - 404
  - name: Mastodon
    url: https://mastodon.erdbeerbaerlp.de
  - name: Switch LAN-Play Server
    url: http://erdbeerbaerlp.de:11451
  - name: Discord Integration Minecraft Server
    check: "tcp-ping"
    url: erdbeerbaerlp.de
    port: 25565

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.erdbeerbaerlp.de
  theme: dark
  # baseUrl: /your-repo-name
  name: ErdbeerbaerLP
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
